<?php

namespace Database\Seeders;

use App\Models\Dataset;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatasetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datasets = array(
            array(
                "id" => 1,
                "tgl" => "2025-08-10",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 2,
                "tgl" => "2025-08-11",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 3,
                "tgl" => "2025-08-12",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 4,
                "tgl" => "2025-08-13",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 5,
                "tgl" => "2025-08-14",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 6,
                "tgl" => "2025-08-15",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 7,
                "tgl" => "2025-08-16",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 8,
                "tgl" => "2025-08-17",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 9,
                "tgl" => "2025-08-18",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 10,
                "tgl" => "2025-08-19",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 11,
                "tgl" => "2025-08-20",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 12,
                "tgl" => "2025-08-21",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 13,
                "tgl" => "2025-08-22",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 14,
                "tgl" => "2025-08-23",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 15,
                "tgl" => "2025-08-24",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 16,
                "tgl" => "2025-08-25",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 17,
                "tgl" => "2025-08-26",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 18,
                "tgl" => "2025-08-27",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 19,
                "tgl" => "2025-08-28",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 20,
                "tgl" => "2025-08-29",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 21,
                "tgl" => "2025-08-30",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 22,
                "tgl" => "2025-08-31",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 23,
                "tgl" => "2025-09-01",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 24,
                "tgl" => "2025-09-02",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 25,
                "tgl" => "2025-09-03",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 26,
                "tgl" => "2025-09-04",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 27,
                "tgl" => "2025-09-05",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 28,
                "tgl" => "2025-09-06",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 29,
                "tgl" => "2025-09-07",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 30,
                "tgl" => "2025-09-08",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 31,
                "tgl" => "2025-09-09",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 32,
                "tgl" => "2025-09-10",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 33,
                "tgl" => "2025-09-11",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 34,
                "tgl" => "2025-09-12",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 35,
                "tgl" => "2025-09-13",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 36,
                "tgl" => "2025-09-14",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 37,
                "tgl" => "2025-09-15",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 38,
                "tgl" => "2025-09-16",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 39,
                "tgl" => "2025-09-17",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 40,
                "tgl" => "2025-09-18",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 41,
                "tgl" => "2025-09-19",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 42,
                "tgl" => "2025-09-20",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 43,
                "tgl" => "2025-09-21",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 44,
                "tgl" => "2025-09-22",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 45,
                "tgl" => "2025-09-23",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 46,
                "tgl" => "2025-09-24",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 47,
                "tgl" => "2025-09-25",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 48,
                "tgl" => "2025-09-26",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 49,
                "tgl" => "2025-09-27",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 50,
                "tgl" => "2025-09-28",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 51,
                "tgl" => "2025-09-29",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 52,
                "tgl" => "2025-09-30",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 53,
                "tgl" => "2025-10-01",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 54,
                "tgl" => "2025-10-02",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 55,
                "tgl" => "2025-10-03",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 56,
                "tgl" => "2025-10-04",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 57,
                "tgl" => "2025-10-05",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 58,
                "tgl" => "2025-10-06",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 59,
                "tgl" => "2025-10-07",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 60,
                "tgl" => "2025-10-08",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 61,
                "tgl" => "2025-10-09",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 62,
                "tgl" => "2025-10-10",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 63,
                "tgl" => "2025-10-11",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 64,
                "tgl" => "2025-10-12",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 65,
                "tgl" => "2025-10-13",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 66,
                "tgl" => "2025-10-14",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 67,
                "tgl" => "2025-10-15",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 68,
                "tgl" => "2025-10-16",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 69,
                "tgl" => "2025-10-17",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 70,
                "tgl" => "2025-10-18",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 71,
                "tgl" => "2025-10-19",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 72,
                "tgl" => "2025-10-20",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 73,
                "tgl" => "2025-10-21",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 74,
                "tgl" => "2025-10-22",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 75,
                "tgl" => "2025-10-23",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 76,
                "tgl" => "2025-10-24",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 77,
                "tgl" => "2025-10-25",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 78,
                "tgl" => "2025-10-26",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 79,
                "tgl" => "2025-10-27",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 80,
                "tgl" => "2025-10-28",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 81,
                "tgl" => "2025-10-29",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 82,
                "tgl" => "2025-10-30",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 83,
                "tgl" => "2025-10-31",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 84,
                "tgl" => "2025-11-01",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 85,
                "tgl" => "2025-11-02",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 86,
                "tgl" => "2025-11-03",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 87,
                "tgl" => "2025-11-04",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 88,
                "tgl" => "2025-11-05",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 89,
                "tgl" => "2025-11-06",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 90,
                "tgl" => "2025-11-07",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 91,
                "tgl" => "2025-11-08",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 92,
                "tgl" => "2025-11-09",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 93,
                "tgl" => "2025-11-10",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 94,
                "tgl" => "2025-11-11",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 95,
                "tgl" => "2025-11-12",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 96,
                "tgl" => "2025-11-13",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 97,
                "tgl" => "2025-11-14",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 98,
                "tgl" => "2025-11-15",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 99,
                "tgl" => "2025-11-16",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 100,
                "tgl" => "2025-11-17",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 101,
                "tgl" => "2025-11-18",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 102,
                "tgl" => "2025-11-19",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 103,
                "tgl" => "2025-11-20",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 104,
                "tgl" => "2025-11-21",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 105,
                "tgl" => "2025-11-22",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 106,
                "tgl" => "2025-11-23",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 107,
                "tgl" => "2025-11-24",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 108,
                "tgl" => "2025-11-25",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 109,
                "tgl" => "2025-11-26",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 110,
                "tgl" => "2025-11-27",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 111,
                "tgl" => "2025-11-28",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 112,
                "tgl" => "2025-11-29",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 113,
                "tgl" => "2025-11-30",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 114,
                "tgl" => "2025-12-01",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 115,
                "tgl" => "2025-12-02",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 116,
                "tgl" => "2025-12-03",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 117,
                "tgl" => "2025-12-04",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 118,
                "tgl" => "2025-12-05",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 119,
                "tgl" => "2025-12-06",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 120,
                "tgl" => "2025-12-07",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 121,
                "tgl" => "2025-12-08",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 122,
                "tgl" => "2025-12-09",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 123,
                "tgl" => "2025-12-10",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 124,
                "tgl" => "2025-12-11",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 125,
                "tgl" => "2025-12-12",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 126,
                "tgl" => "2025-12-13",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 127,
                "tgl" => "2025-12-14",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 128,
                "tgl" => "2025-12-15",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 129,
                "tgl" => "2025-12-16",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 130,
                "tgl" => "2025-12-17",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 131,
                "tgl" => "2025-12-18",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 132,
                "tgl" => "2025-12-19",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 133,
                "tgl" => "2025-12-20",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 134,
                "tgl" => "2025-12-21",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 135,
                "tgl" => "2025-12-22",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 136,
                "tgl" => "2025-12-23",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 137,
                "tgl" => "2025-12-24",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 138,
                "tgl" => "2025-12-25",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 139,
                "tgl" => "2025-12-26",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 140,
                "tgl" => "2025-12-27",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 141,
                "tgl" => "2025-12-28",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 142,
                "tgl" => "2025-12-29",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 143,
                "tgl" => "2025-12-30",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 144,
                "tgl" => "2025-12-31",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 145,
                "tgl" => "2026-01-01",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 146,
                "tgl" => "2026-01-02",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 147,
                "tgl" => "2026-01-03",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 148,
                "tgl" => "2026-01-04",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 149,
                "tgl" => "2026-01-05",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 150,
                "tgl" => "2026-01-06",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 151,
                "tgl" => "2026-01-07",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 152,
                "tgl" => "2026-01-08",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 153,
                "tgl" => "2026-01-09",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 154,
                "tgl" => "2026-01-10",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 155,
                "tgl" => "2026-01-11",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 156,
                "tgl" => "2026-01-12",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 157,
                "tgl" => "2026-01-13",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 158,
                "tgl" => "2026-01-14",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 159,
                "tgl" => "2026-01-15",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 160,
                "tgl" => "2026-01-16",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 161,
                "tgl" => "2026-01-17",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 162,
                "tgl" => "2026-01-18",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 163,
                "tgl" => "2026-01-19",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 164,
                "tgl" => "2026-01-20",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 165,
                "tgl" => "2026-01-21",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 166,
                "tgl" => "2026-01-22",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 167,
                "tgl" => "2026-01-23",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 168,
                "tgl" => "2026-01-24",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 169,
                "tgl" => "2026-01-25",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 170,
                "tgl" => "2026-01-26",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 171,
                "tgl" => "2026-01-27",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 172,
                "tgl" => "2026-01-28",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 173,
                "tgl" => "2026-01-29",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 174,
                "tgl" => "2026-01-30",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 175,
                "tgl" => "2026-01-31",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 176,
                "tgl" => "2026-02-01",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 177,
                "tgl" => "2026-02-02",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 178,
                "tgl" => "2026-02-03",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 179,
                "tgl" => "2026-02-04",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 180,
                "tgl" => "2026-02-05",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 181,
                "tgl" => "2026-02-06",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 182,
                "tgl" => "2026-02-07",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 183,
                "tgl" => "2026-02-08",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 184,
                "tgl" => "2026-02-09",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 185,
                "tgl" => "2026-02-10",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 186,
                "tgl" => "2026-02-11",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 187,
                "tgl" => "2026-02-12",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 188,
                "tgl" => "2026-02-13",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 189,
                "tgl" => "2026-02-14",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 190,
                "tgl" => "2026-02-15",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 191,
                "tgl" => "2026-02-16",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 192,
                "tgl" => "2026-02-17",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 193,
                "tgl" => "2026-02-18",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 194,
                "tgl" => "2026-02-19",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 195,
                "tgl" => "2026-02-20",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 196,
                "tgl" => "2026-02-21",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
        );
        Dataset::insert($datasets);
    }
}
