<?php

namespace Database\Seeders;

use App\Models\Dataset;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatasetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datasets = array(
            array(
                "id" => 1,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 2,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 3,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 4,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 5,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 6,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 7,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 8,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 9,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 10,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 11,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 12,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 13,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 14,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 15,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 16,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 17,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 18,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 19,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 20,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 21,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 22,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 23,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 24,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 25,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 26,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 27,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 28,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 29,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 30,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 31,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 32,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 33,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 34,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 35,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 36,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 37,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 38,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 39,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 40,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 41,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 42,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 43,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 44,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 45,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 46,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 47,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 48,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 49,
                "tgl" => "0000-00-00",
                "label" => "gizi buruk",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 50,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 51,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 52,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 53,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 54,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 55,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 56,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 57,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 58,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 59,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 60,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 61,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 62,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 63,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 64,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 65,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 66,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 67,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 68,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 69,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 70,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 71,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 72,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 73,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 74,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 75,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 76,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 77,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 78,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 79,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 80,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 81,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 82,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 83,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 84,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 85,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 86,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 87,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 88,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 89,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 90,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 91,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 92,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 93,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 94,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 95,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 96,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 97,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 98,
                "tgl" => "0000-00-00",
                "label" => "gizi kurang",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 99,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 100,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 101,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 102,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 103,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 104,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 105,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 106,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 107,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 108,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 109,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 110,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 111,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 112,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 113,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 114,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 115,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 116,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 117,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 118,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 119,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 120,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 121,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 122,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 123,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 124,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 125,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 126,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 127,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 128,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 129,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 130,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 131,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 132,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 133,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 134,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 135,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 136,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 137,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 138,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 139,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 140,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 141,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 142,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 143,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 144,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 145,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 146,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 147,
                "tgl" => "0000-00-00",
                "label" => "gizi baik",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 148,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 149,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 150,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 151,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 152,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 153,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 154,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 155,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 156,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 157,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 158,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 159,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 160,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 161,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 162,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 163,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 164,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 165,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 166,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 167,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 168,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 169,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 170,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 171,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 172,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 173,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 174,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 175,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 176,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 177,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 178,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 179,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 180,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 181,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 182,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 183,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 184,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 185,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 186,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 187,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 188,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 189,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 190,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 191,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 192,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 193,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 194,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 195,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 196,
                "tgl" => "0000-00-00",
                "label" => "gizi lebih",
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
        );

        Dataset::insert($datasets);
    }
}
